language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - docker build --tag npm-mirror .
  - docker run --detach --publish 4873:4873 npm-mirror

script:
  - netstat -ln | grep 4873
